public class BalanceChkResp{
    public String MESSAGE{set;get;}    //Processed
    public String STATUS{set;get;}    //Success
    public Double CUST_BAL_UNAPP{set;get;}    //135798.47
    public String REFUNDTYPE{set;get;}    //DEP
    public Double CUST_BAL_OPEN_INV{set;get;}    //0
    public String ACCOUNTNUMBER{set;get;}    //TDD-17361

    }

     ///Content Starts Here{"MESSAGE":"Please verify the input details :-The result of from-spec is null.", "STATUS":"Error", "REFUNDTYPE":"DEP", "ACCOUNTNUMBER":"TDD-118543"}
///{"MESSAGE":"Processed", "STATUS":"Success", "CUST_BAL_UNAPP":135793.97, "REFUNDTYPE":"DEP", "CUST_BAL_OPEN_INV":0.0, "ACCOUNTNUMBER":"TDD-17361"}