public class CMDMFuApp {

    public String BusinessUnitName {set;get;}    //AXS: AXS FZ
    public String CreditMemoTrxId {set;get;}//300000241362044
    public String DebitMemoTrxId {set;get;}    //716222
    public Decimal AmountApplied {set;get;}    //100
    public String InvoiceLineNumber {set;get;}    //1
    public String GlDate {set;get;}    //2023-05-02
    public String ApplyDate {set;get;}     //2023-05-02

}