public class customerRefund{
    public Decimal REFUND_AMOUNT {set;get;}    //1000
    public String REFUND_TYPE{set;get;}    //DEP
    public String REFUND_DATE{set;get;}    //2025-04-28
    public String ACCOUNT_NUMBER{set;get;}    //TDD-17361
    public String ACCOUNTING_DATE{set;get;}    //2025-04-28
    public String REFUND_PAYMENT_METHOD{set;get;}    //NULL
    public String REFUND_REFERENCE_ID{set;get;}    //T2025043794708
    public String REMITTANCE_MESSAGE_1{set;get;}
    public String REMITTANCE_MESSAGE_2{set;get;}
}