public class ReceiptFusion {

    public Decimal Amount{set;get;}    //1.9
    public String CurrencyCode{set;get;}    //AED
    public String DepositDate{set;get;}    //2023-01-28
    public String GlDate{set;get;}    //2023-01-28
    public String IssueDate{set;get;}    //2023-01-28
    public String ReceiptDate{set;get;}    //2023-01-28
    public String ReceiptNumber{set;get;}    //AXSReceipt50ww2
    public String ReceiptMethodName{set;get;}
    public String CustomerSiteName{set;get;}
    public String BusinessUnitName{set;get;}
    public String CustomerAccountNumber{set;get;}
    public String MaturityDate{set;get;}
    public String FLEXContext{set;get;}
    public String AxsReference{set;get;}
    public String Issuer{set;get;}
    public String StructuredPaymentReference{set;get;}// auth code
    public String Comments{set;get;}

}