@isTest
private class ReceiptFusionTest {
      static testmethod void meth1() {
      Test.startTest();
      ReceiptFusion r=new ReceiptFusion();
        r.Amount=null;
        r.CurrencyCode=null;
        r.DepositDate=null;
        r.GlDate=null;
        r.IssueDate=null;
        r.ReceiptDate=null;
        r.ReceiptNumber=null;
        r.ReceiptMethodName=null;
        r.CustomerSiteName=null;
        r.BusinessUnitName=null;
        r.CustomerAccountNumber=null;
        r.MaturityDate=null;
        r.FLEXContext=null;
        r.AxsReference=null;
        r.Issuer=null;
        r.StructuredPaymentReference=null;
        r.Comments=null;

      Test.stopTest();

      }

}