public class SingleDocUploadJSONWrapper {
    public cls_Documents Documents;
    public String applicationId;    //21920100325397
    public class cls_Documents {
        public String documentTypeId;    //50f41f94-b59b-4482-871e-2eff765aa5ba
        public String document;    //
        public boolean IsMandatory;
        public String MimeType;    //image/jpeg
        public String documentNameEn;    //Personal Photo
        public String documentNameAr;    //صورة شخصية
        public String FileName;    //11.jpg
    }
}